language: node_js
node_js:
- '6'

before_install:
- openssl aes-256-cbc -K $encrypted_ba7744bad3a2_key -iv $encrypted_ba7744bad3a2_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "${USERNAME}"
- git config --global user.email "${EMAIL}"

install:
- npm install

script:
- git clone "git@github.com:pengttyy/pengttyy.github.io.git" public
- hexo g
- cd ./public
- git status
- git add .
- git commit -m "Travis CI generate push"
- git push origin master:master

branches:
  only:
  - blogSource

env:
  global:
  - secure: V3XIkOIj+2zeEUZQTtpmWRYaemToZHtq40MIkRqybp25JXD1LHTeFsAZ5zuOjnmMHZWXEmPNDFQ3+qnKQPdH+iXqWG3dGwq1NDlPRlrfBBOQVAm+9c5t4ca4Ptf47/5GP57zlSuhr34ALbyQ2OJDtnIoS0WTfh0xVy2ITm2OjPBW718aKsDcRes+ZD+lmCgd0Gx5VPHUGMVg9ZNAyAbxky+AzA7DXyVG1BCP8bzAL0q9OfBwrBCxWt5M82cwBl3Pc9h5TrWLL/yMMD1YQc/+CRkOZX7o9sc98SkUqxmwfXoU1VhKosQVsTC/AR6sW9+iCLn/Zoifa63yVsk5a8JN6aktU2MoArk1gvJvI1g7aL181ZaG06AnOjVfxS78+8EUrAlCOUgMRIFE2CEhLBhdtbQ/i0PlLqkYGNYLy4euQpvJQ4q7SrJI4gDnPmOLyqBS/qKwBKUbTC6XJOVWTLmdKF62AriD+zq46ge73qALEFFUh34wJhQuQhbgyJF5Dd5OI4Wr81hM0Q6D4RN2159jsPHZy5lrkSIBC8YSa8VdMtzNo37DhO4/j6WFeFzFzgG0T+IeD5cxfD5KhRzZaQbFpyttNLahdMirRofS8CeMWhDnMM6aEUEcJba1m7/igj/Gj3gx3QYhjHBZVHhV5gOgFkb3t40gl0uWE1bym+cwmmI=
  - secure: tEFW7zgtRlP7LzSIyvrLgl31+gIf10YfqUzu173yziYpmdCsYFWqlQGuAdd3/UE4f/NUeSIyCdR0oEUEShbsWRmrlVIZlvAXPVX+w7HUbGHgTDpV/MTsXYmn+gEvdwzOb8VhNbYxrKh/fYy6z0aKTNOFoVADVieWUhhfB6VqEO1VeRnYBydK02DpAURvpxl33K0uHc1rO9ee60FPTg8rU9/0AUROfN8VlXGLDn+vj3dWZjMTbr3z3ItLgbSsJL7JLVxyCJDwutDktnmxFXNv6pTZs1XTdKxHEtgrzol1uFcGQtTG6UugPlgCWRtJTj0lDf3fprWmEKD6raMLY6sFB7JZJGVp56+wfQlJf0oww9MSSKV0JW3RnaeIp4/plFn3EDGglWW10u/+bSxWWozbTnSOcOM3CJjAjCyZ/JXLhXxZF4LYKvd8LQIjrnDFnrhKIONeNHtxaoUyN5KuSamhkvDjptWUH39qshZJiMzGzVRdoD7UK+6et+VjQSY8QcvTe4vvU6dG4FI5aMH0tj4krlaZyeRKd2ThJ3ScGJEdeEkQsoGoF07ypGo7oCmXL3WNOJmW4TbsTwKQqJlFZcIm/XEgxFE+TQw6/wgA9bYSCN/VdXFriYomzmAvJ9WHAHY/MOreAhcNa9bL3/3YEW8jQGlFfLPGf/ASRve2N6YzukM=

cache:
  directories:
    - node_modules